-- create table team (
--     id int primary key not null,
--     name_team varchar(20),
--     id_play int
--     );
-- create table play(
--     id int primary key not null,
--     dateplay date,
--     stadium varchar(100),
--     team1 serial,
--     team2 serial
--     );
--
-- create table player(
--     id int primary key not null,
--     name_player varchar(20),
--     nombre int ,
--     id_team int
--     );
--
-- create table sponsor(
--     id int primary key not null,
--     name_sponsor varchar(20)
--     );
--
-- create table have (
--     id int primary key not null,
--     id_team int ,
--     id_sponsor int
--     );
-- create table goal (
--     id int primary key
-- );
--
-- create table score (
--     id int primary key ,
--     score_a int,
--     score_b int,
--     timeplay int,
--     id_play int,
--     id_player int,
--     isOnGoal boolean
--     /*
-- -- @ManyToOne
--     @JoinColumn(name = "score_a")
--     private Team score_a;
-- @ManyToOne
--     @JoinColumn(name = "score_b")
--     private Team score_b;
-- @ManyToOne
--     @JoinColumn(name = "id")
--     private Play id_play;
-- @ManyToOne
--     @JoinColumn(name = "id")
--     private Player id_player;
-- @ManyToOne
--     @JoinColumn(name = "name_player")
--     private Player isOnGoal;
-- */
-- )
--
--
